version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev # grab the docker file configuration
    volumes:
      - ./src:/app/src # Links the source files to the running container
    ports:
      - "3000:8000" # open port 3000 for 8000